import json
import re
import sys
from pathlib import Path

try:
    from openpyxl import load_workbook
except ImportError:
    print('Missing Python dependency: openpyxl', file=sys.stderr)
    print('Install it with: python -m pip install openpyxl', file=sys.stderr)
    sys.exit(2)


ROOT_DIR = Path(__file__).resolve().parents[1]
WORKBOOK_PATH = ROOT_DIR / 'tools' / 'menu-workbook' / 'menu-data.xlsx'
DATA_DIR = ROOT_DIR / 'miniprogram' / 'data'
PLACEHOLDER_IMAGE = '../../assets/placeholder-food.jpg'
FOOD_IMAGE_PREFIX = '../../assets/foods/'

TAG_SPLIT_RE = re.compile(r'[、,，;；\n]+')
CHOICE_SPLIT_RE = re.compile(r'[、,，;；|]+')
OPTION_SEPARATOR_RE = re.compile(r'[:：]')
OPTIONAL_MARKERS = ('(可选)', '（可选）', '[可选]', '【可选】', '(optional)')


class MenuDataError(Exception):
    pass


def normalize_text(value):
    if value is None:
        return ''
    return str(value).strip()


def normalize_number(value):
    if value is None or str(value).strip() == '':
        return 0
    try:
        return int(value)
    except (TypeError, ValueError):
        try:
            return float(value)
        except (TypeError, ValueError):
            return 0


def image_path(image_file):
    value = normalize_text(image_file)
    if not value:
        return PLACEHOLDER_IMAGE
    if value.startswith('../') or value.startswith('..\\') or '/' in value or '\\' in value:
        return value.replace('\\', '/')
    return FOOD_IMAGE_PREFIX + value


def js_file(name, value):
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    output = DATA_DIR / name
    text = [
        '// This file is generated by tools/generate-menu-data.py. Do not edit manually.',
        'export default ' + json.dumps(value, ensure_ascii=False, indent=2),
        ''
    ]
    output.write_text('\n'.join(text), encoding='utf-8')


def read_sheet(workbook, sheet_name, required_headers, row_headers=None):
    if sheet_name not in workbook.sheetnames:
        raise MenuDataError(f'工作簿缺少 Sheet：{sheet_name}')

    sheet = workbook[sheet_name]
    headers = [normalize_text(cell.value) for cell in sheet[1]]
    for header in required_headers:
        if header not in headers:
            raise MenuDataError(f'{sheet_name} 缺少字段：{header}')

    row_headers = row_headers or required_headers
    rows = []
    for row_index, row in enumerate(sheet.iter_rows(min_row=2, values_only=True), start=2):
        record = {'__line': row_index}
        for index, header in enumerate(headers):
            if header:
                record[header] = normalize_text(row[index] if index < len(row) else '')

        if any(record.get(header, '') for header in row_headers):
            rows.append(record)

    return rows


def ensure_required(record, fields, sheet_name):
    for field in fields:
        if not record.get(field):
            raise MenuDataError(f'{sheet_name} 第 {record["__line"]} 行缺少必填字段：{field}')


def ensure_unique(records, key_fn, sheet_name, label):
    seen = {}
    for record in records:
        key = key_fn(record)
        if not key:
            continue
        if key in seen:
            raise MenuDataError(
                f'{sheet_name} 存在重复{label}：{key}，行号 {seen[key]} / {record["__line"]}'
            )
        seen[key] = record['__line']


def split_unique(text, splitter):
    result = []
    seen = set()
    for item in splitter.split(normalize_text(text)):
        value = item.strip()
        if value and value not in seen:
            result.append(value)
            seen.add(value)
    return result


def parse_tags(value):
    return split_unique(value, TAG_SPLIT_RE)


def option_id(group_name):
    slug = re.sub(r'[^0-9A-Za-z]+', '-', group_name).strip('-').lower()
    return slug or group_name


def parse_option_group_name(raw_name):
    group_name = normalize_text(raw_name)
    required = True
    lowered = group_name.lower()

    for marker in OPTIONAL_MARKERS:
        if marker in group_name or marker in lowered:
            group_name = group_name.replace(marker, '').replace(marker.lower(), '').strip()
            required = False

    return group_name, required


def parse_options(value, dish):
    text = normalize_text(value)
    if not text:
        return []

    options = []
    seen_group_ids = set()
    for raw_line in text.splitlines():
        line = normalize_text(raw_line)
        if not line:
            continue

        parts = OPTION_SEPARATOR_RE.split(line, maxsplit=1)
        if len(parts) != 2:
            raise MenuDataError(
                f'Dishes 第 {dish["__line"]} 行 options 格式错误：{line}；'
                '请使用“规格名: 选项一、选项二”的格式'
            )

        group_name, required = parse_option_group_name(parts[0])
        choices = split_unique(parts[1], CHOICE_SPLIT_RE)
        if not group_name:
            raise MenuDataError(f'Dishes 第 {dish["__line"]} 行 options 存在空规格名')
        if not choices:
            raise MenuDataError(f'Dishes 第 {dish["__line"]} 行规格“{group_name}”没有任何选项')

        group_id = option_id(group_name)
        if group_id in seen_group_ids:
            raise MenuDataError(f'Dishes 第 {dish["__line"]} 行存在重复规格组：{group_name}')
        seen_group_ids.add(group_id)

        options.append({
            'id': group_id,
            'name': group_name,
            'required': required,
            'choices': choices,
        })

    return options


def build_shop(workbook):
    rows = read_sheet(workbook, 'Shop', [
        'name',
        'subtitle',
        'shareTitle',
        'shareImage',
        'pageBackgroundImage',
        'headerBackgroundImage',
        'headerBackgroundPosition'
    ])
    if len(rows) != 1:
        raise MenuDataError('Shop 只能保留一行店铺配置')

    shop = rows[0]
    ensure_required(shop, ['name', 'subtitle', 'shareTitle'], 'Shop')
    return {
        'name': shop['name'],
        'subtitle': shop['subtitle'],
        'shareTitle': shop['shareTitle'],
        'shareImage': shop['shareImage'],
        'pageBackgroundImage': shop['pageBackgroundImage'],
        'headerBackgroundImage': shop['headerBackgroundImage'],
        'headerBackgroundPosition': shop['headerBackgroundPosition'],
    }


def build_categories(workbook):
    rows = read_sheet(workbook, 'Categories', ['categoryId', 'categoryName', 'order'])
    for row in rows:
        ensure_required(row, ['categoryId', 'categoryName'], 'Categories')
    ensure_unique(rows, lambda row: row['categoryId'], 'Categories', '分类 ID')

    return sorted([
        {
            'id': row['categoryId'],
            'name': row['categoryName'],
            'order': normalize_number(row['order']),
        }
        for row in rows
    ], key=lambda row: row['order'])


def build_dishes(workbook, categories):
    dishes = read_sheet(
        workbook,
        'Dishes',
        [
            'dishId',
            'dishName',
            'categoryId',
            'categoryName',
            'order',
            'desc',
            'price',
            'imageFile',
            'tags',
            'options'
        ],
        row_headers=['dishId', 'dishName', 'categoryId']
    )
    category_ids = {category['id'] for category in categories}

    for dish in dishes:
        ensure_required(dish, ['dishId', 'dishName', 'categoryId'], 'Dishes')
        if dish['categoryId'] not in category_ids:
            raise MenuDataError(
                f'Dishes 第 {dish["__line"]} 行引用了不存在的分类 ID：{dish["categoryId"]}'
            )
    ensure_unique(dishes, lambda row: row['dishId'], 'Dishes', '商品 ID')

    return [
        {
            'id': dish['dishId'],
            'categoryId': dish['categoryId'],
            'order': normalize_number(dish['order']),
            'name': dish['dishName'],
            'desc': dish['desc'],
            'price': dish['price'] or '0',
            'image': image_path(dish['imageFile']),
            'tags': parse_tags(dish.get('tags', '')),
            'options': parse_options(dish.get('options', ''), dish),
        }
        for dish in sorted(dishes, key=lambda row: normalize_number(row['order']))
    ]


def main():
    if not WORKBOOK_PATH.exists():
        raise MenuDataError(f'找不到工作簿：{WORKBOOK_PATH}')

    workbook = load_workbook(WORKBOOK_PATH, data_only=False)
    shop = build_shop(workbook)
    categories = build_categories(workbook)
    dishes = build_dishes(workbook, categories)

    js_file('shop-data.js', shop)
    js_file('category-data.js', categories)
    js_file('dish-data.js', dishes)

    print('Generated menu data from Excel workbook:')
    print('- tools/menu-workbook/menu-data.xlsx')
    print('- miniprogram/data/shop-data.js')
    print('- miniprogram/data/category-data.js')
    print('- miniprogram/data/dish-data.js')


if __name__ == '__main__':
    try:
        main()
    except MenuDataError as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
